import os
import re
import time
import logging
import requests
from pathlib import Path
import dotenv
from backend.agent.state import AgentState
from langchain_core.messages import AIMessage, ToolMessage, SystemMessage
from langchain_ollama import ChatOllama
from langchain_core.tools import tool

logger = logging.getLogger("aidock.agent.nodes")

# Load .env looking upwards from this file
dotenv.load_dotenv(dotenv.find_dotenv())

def make_workspace_tools(session_id: str):
    """
    Creates curried tools bound to the active session_id's sandboxed workspace.
    """
    base_workspace = Path("/workspace")
    project_workspace = base_workspace / session_id
    project_workspace.mkdir(parents=True, exist_ok=True)
    
    @tool
    def list_files() -> str:
        """
        Recursively scan the workspace directory and return a list of all files, including their paths and sizes in bytes.
        """
        try:
            files = []
            for path in project_workspace.rglob("*"):
                if path.is_file():
                    rel_path = path.relative_to(project_workspace)
                    files.append(f"- {rel_path} ({path.stat().st_size} bytes)")
            if not files:
                return "Workspace is empty."
            return "\n".join(files)
        except Exception as e:
            return f"Error scanning workspace: {str(e)}"

    @tool
    def read_file(file_path: str) -> str:
        """
        Read the contents of a file in the workspace. file_path should be relative to the workspace root.
        """
        target_path = (project_workspace / file_path).resolve()
        if not str(target_path).startswith(str(project_workspace.resolve())):
            return "Access denied: outside workspace boundary."
        if not target_path.exists() or not target_path.is_file():
            return f"File {file_path} not found."
        try:
            with open(target_path, "r", encoding="utf-8") as f:
                return f.read()
        except Exception as e:
            return f"Error reading file: {str(e)}"

    @tool
    def write_file(file_path: str, content: str) -> str:
        """
        Write or update a file in the workspace with the specified content. file_path should be relative to the workspace root.
        """
        target_path = (project_workspace / file_path).resolve()
        if not str(target_path).startswith(str(project_workspace.resolve())):
            return "Access denied: outside workspace boundary."
        try:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(content)
            return f"File {file_path} written successfully."
        except Exception as e:
            return f"Error writing file: {str(e)}"

    @tool
    def delete_file(file_path: str) -> str:
        """
        Delete a file from the workspace. file_path should be relative to the workspace root.
        """
        target_path = (project_workspace / file_path).resolve()
        if not str(target_path).startswith(str(project_workspace.resolve())):
            return "Access denied: outside workspace boundary."
        if not target_path.exists() or not target_path.is_file():
            return f"File {file_path} not found."
        try:
            target_path.unlink()
            return f"File {file_path} deleted successfully."
        except Exception as e:
            return f"Error deleting file: {str(e)}"

    return [list_files, read_file, write_file, delete_file]

def call_tools_node(state: AgentState):
    """
    Executes tool calls generated by the LLM and appends the resulting ToolMessages.
    """
    session_id = state.get("session_id", "default_session")
    messages = state.get("messages", [])
    last_message = messages[-1]
    
    tools = make_workspace_tools(session_id)
    tools_map = {t.name: t for t in tools}
    
    tool_messages = []
    if hasattr(last_message, "tool_calls"):
        for tool_call in last_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            tool_id = tool_call["id"]
            
            logger.info(f"Executing tool '{tool_name}' with args {tool_args}")
            if tool_name in tools_map:
                try:
                    result = tools_map[tool_name].invoke(tool_args)
                    tool_messages.append(ToolMessage(content=str(result), tool_call_id=tool_id))
                except Exception as e:
                    tool_messages.append(ToolMessage(content=f"Error executing tool: {str(e)}", tool_call_id=tool_id))
            else:
                tool_messages.append(ToolMessage(content=f"Tool {tool_name} not found.", tool_call_id=tool_id))
                
    return {"messages": tool_messages}

def init_node(state: AgentState):
    """Initialize the workspace for this session."""
    session_id = state.get("session_id", "default_session")
    # Base workspace path from Docker mount
    base_workspace = Path("/workspace")
    
    # Create isolated sub-folder for this chat cycle
    project_workspace = base_workspace / session_id
    project_workspace.mkdir(parents=True, exist_ok=True)
    
    return {"workspace_path": str(project_workspace)}

def reason_node(state: AgentState):
    """Reasoning node that calls the local LLM."""
    # Detect if running inside a Docker container
    in_docker = os.getenv("CONTAINER_MODE") == "true" or os.path.exists('/.dockerenv') or Path('/workspace').exists()
    
    # Default model-runner base URL: internal DNS in Docker, localhost on the host
    default_base_url = "http://model-runner.docker.internal" if in_docker else "http://localhost:12434"
    base_url = os.getenv("LLM_BASE_URL", default_base_url)
    
    # Prefer per-request model slug if provided (validated), else resolve env
    # Simple cache for allowed models list to avoid frequent API calls
    _models_cache: dict = globals().get("_models_cache") or {"ts": 0, "models": []}

    def fetch_allowed_slugs() -> list:
        # Priority: explicit env var LLM_ALLOWED_MODELS (comma separated)
        env_list = os.getenv("LLM_ALLOWED_MODELS")
        if env_list:
            return [s.strip() for s in env_list.split(",") if s.strip()]

        # Next priority: server-managed whitelist file
        wl_file = os.getenv("LLM_WHITELIST_FILE", "./backend/llm_whitelist.json")
        try:
            p = Path(wl_file)
            if p.exists():
                data = p.read_text(encoding="utf-8")
                import json
                parsed = json.loads(data)
                if isinstance(parsed, list):
                    return [s for s in parsed if isinstance(s, str)]
        except Exception as e:
            logger.debug(f"Failed reading whitelist file {wl_file}: {e}")

        api_url = os.getenv("CODEXSPACE_API_URL")
        api_key = os.getenv("CODEXSPACE_API_KEY")
        if not api_url or not api_key:
            return []

        # Cache for 60 seconds
        now = time.time()
        if _models_cache.get("ts", 0) + 60 > now and _models_cache.get("models"):
            return _models_cache["models"]

        try:
            resp = requests.get(f"{api_url.rstrip('/')}/models", headers={"Authorization": f"Bearer {api_key}"}, timeout=5)
            resp.raise_for_status()
            data = resp.json()
            slugs = []
            for item in data:
                if isinstance(item, dict) and "slug" in item:
                    slugs.append(item["slug"])
                elif isinstance(item, str):
                    slugs.append(item)
            _models_cache["ts"] = now
            _models_cache["models"] = slugs
            globals()["_models_cache"] = _models_cache
            return slugs
        except Exception as e:
            logger.warning(f"Could not fetch allowed slugs from CodexSpace: {e}")
            return []

    def is_valid_slug(slug: str) -> bool:
        # Allow patterns like owner/model or owner/model:tag with safe chars
        pattern = r'^[a-z0-9._-]+/[a-z0-9._-]+(:[A-Za-z0-9._-]+)?$'
        if not re.match(pattern, slug):
            return False

        # If there's an explicit allow-list, require membership
        allowed = fetch_allowed_slugs()
        if allowed:
            return slug in allowed

        # No allow-list configured; accept on pattern match only
        return True

    model = None
    model_slug = state.get("model_slug")
    if model_slug and isinstance(model_slug, str) and is_valid_slug(model_slug):
        model = model_slug

    if not model:
        # Fall back to configured environment variables
        model = os.getenv("LLM_MODEL_NAME")
        if not model:
            image = os.getenv("LLM_IMAGE", "ai/mistral:7B-Q4_K_M")
            model = f"docker.io/{image}"

    llm = ChatOllama(model=model, base_url=base_url)
    
    session_id = state.get("session_id", "default_session")
    tools = make_workspace_tools(session_id)
    
    messages = list(state.get("messages", []))
    # Prepend SystemMessage to explain tools context
    if not any(isinstance(m, SystemMessage) for m in messages):
        system_content = (
            "You are the AIDock Orchestrator Agent. You have access to the user's sandboxed workspace "
            "via filesystem tools. You can use these tools to scan files, read files, write files, or delete files "
            "in the workspace. Always use the appropriate tool to perform these actions when requested."
        )
        messages.insert(0, SystemMessage(content=system_content))
    
    try:
        llm_with_tools = llm.bind_tools(tools)
        logger.info(f"LLM Reasoning - invoking model: {model} with tool binding...")
        response = llm_with_tools.invoke(messages)
    except Exception as e:
        logger.warning(f"Failed to bind tools or invoke with tools: {e}. Falling back to standard invoke.")
        response = llm.invoke(messages)
        
    logger.info(f"LLM Reasoning - model response received (length: {len(response.content)} chars)")
    
    has_tool_calls = hasattr(response, "tool_calls") and len(response.tool_calls) > 0
    return {"messages": [response], "is_complete": not has_tool_calls}
